// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.2
//   protoc               v6.30.2
// source: message_signaling.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "api.webrtc.v1";

/**
 * 定义消息结构,协调通信的过程，系列命令
 * 发送给 server 的信息
 */
export interface SignalingShell {
  ForwardPublicKey: Buffer;
  /** 加密数据 */
  Data: Buffer;
}

function createBaseSignalingShell(): SignalingShell {
  return { ForwardPublicKey: Buffer.alloc(0), Data: Buffer.alloc(0) };
}

export const SignalingShell: MessageFns<SignalingShell> = {
  encode(message: SignalingShell, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ForwardPublicKey.length !== 0) {
      writer.uint32(10).bytes(message.ForwardPublicKey);
    }
    if (message.Data.length !== 0) {
      writer.uint32(18).bytes(message.Data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalingShell {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalingShell();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ForwardPublicKey = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.Data = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignalingShell {
    return {
      ForwardPublicKey: isSet(object.ForwardPublicKey)
        ? Buffer.from(bytesFromBase64(object.ForwardPublicKey))
        : Buffer.alloc(0),
      Data: isSet(object.Data) ? Buffer.from(bytesFromBase64(object.Data)) : Buffer.alloc(0),
    };
  },

  toJSON(message: SignalingShell): unknown {
    const obj: any = {};
    if (message.ForwardPublicKey.length !== 0) {
      obj.ForwardPublicKey = base64FromBytes(message.ForwardPublicKey);
    }
    if (message.Data.length !== 0) {
      obj.Data = base64FromBytes(message.Data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SignalingShell>, I>>(base?: I): SignalingShell {
    return SignalingShell.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignalingShell>, I>>(object: I): SignalingShell {
    const message = createBaseSignalingShell();
    message.ForwardPublicKey = object.ForwardPublicKey ?? Buffer.alloc(0);
    message.Data = object.Data ?? Buffer.alloc(0);
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
