// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgKind int32

const (
	MsgKind_KIND_UNSPECIFIED  MsgKind = 0
	MsgKind_KIND_ERROR        MsgKind = 1
	MsgKind_KIND_WS_SIGNALING MsgKind = 2
)

// Enum value maps for MsgKind.
var (
	MsgKind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_ERROR",
		2: "KIND_WS_SIGNALING",
	}
	MsgKind_value = map[string]int32{
		"KIND_UNSPECIFIED":  0,
		"KIND_ERROR":        1,
		"KIND_WS_SIGNALING": 2,
	}
)

func (x MsgKind) Enum() *MsgKind {
	p := new(MsgKind)
	*p = x
	return p
}

func (x MsgKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgKind) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MsgKind) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MsgKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgKind.Descriptor instead.
func (MsgKind) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          MsgKind                `protobuf:"varint,1,opt,name=kind,proto3,enum=api.webrtc.v1.MsgKind" json:"kind,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`             // 全局唯一 ID
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // 关联请求/响应 ID
	Ts            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`                                            // 发送时间
	FromPubkey    []byte                 `protobuf:"bytes,5,opt,name=from_pubkey,json=fromPubkey,proto3" json:"from_pubkey,omitempty"`          // 发送方公钥
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetKind() MsgKind {
	if x != nil {
		return x.Kind
	}
	return MsgKind_KIND_UNSPECIFIED
}

func (x *Header) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Header) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Header) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Header) GetFromPubkey() []byte {
	if x != nil {
		return x.FromPubkey
	}
	return nil
}

type Envelope struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // 协议版本
	Header  *Header                `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	// 安全字段（必填）
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	SignatureAlgo string `protobuf:"bytes,4,opt,name=signature_algo,json=signatureAlgo,proto3" json:"signature_algo,omitempty"` // 如 "ECDSA_P256_SHA256"
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_ErrorReply
	//	*Envelope_WsSignaling
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Envelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Envelope) GetSignatureAlgo() string {
	if x != nil {
		return x.SignatureAlgo
	}
	return ""
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetErrorReply() *ErrorReply {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ErrorReply); ok {
			return x.ErrorReply
		}
	}
	return nil
}

func (x *Envelope) GetWsSignaling() *WSSignaling {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_WsSignaling); ok {
			return x.WsSignaling
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_ErrorReply struct {
	ErrorReply *ErrorReply `protobuf:"bytes,5,opt,name=error_reply,json=errorReply,proto3,oneof"`
}

type Envelope_WsSignaling struct {
	WsSignaling *WSSignaling `protobuf:"bytes,6,opt,name=ws_signaling,json=wsSignaling,proto3,oneof"`
}

func (*Envelope_ErrorReply) isEnvelope_Payload() {}

func (*Envelope_WsSignaling) isEnvelope_Payload() {}

type ErrorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 字符串形式的错误码
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorReply) Reset() {
	*x = ErrorReply{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReply) ProtoMessage() {}

func (x *ErrorReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReply.ProtoReflect.Descriptor instead.
func (*ErrorReply) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorReply) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ErrorReply) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type WSSignaling struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalingType string                 `protobuf:"bytes,1,opt,name=signaling_type,json=signalingType,proto3" json:"signaling_type,omitempty"` // offer, answer, ice
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                        // SDP / ICE / 其他
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSSignaling) Reset() {
	*x = WSSignaling{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSSignaling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSSignaling) ProtoMessage() {}

func (x *WSSignaling) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSSignaling.ProtoReflect.Descriptor instead.
func (*WSSignaling) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *WSSignaling) GetSignalingType() string {
	if x != nil {
		return x.SignalingType
	}
	return ""
}

func (x *WSSignaling) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\rapi.webrtc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x01\n" +
	"\x06Header\x12*\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x16.api.webrtc.v1.MsgKindR\x04kind\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12*\n" +
	"\x02ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1f\n" +
	"\vfrom_pubkey\x18\x05 \x01(\fR\n" +
	"fromPubkey\"\xa2\x02\n" +
	"\bEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12-\n" +
	"\x06header\x18\x02 \x01(\v2\x15.api.webrtc.v1.HeaderR\x06header\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12%\n" +
	"\x0esignature_algo\x18\x04 \x01(\tR\rsignatureAlgo\x12<\n" +
	"\verror_reply\x18\x05 \x01(\v2\x19.api.webrtc.v1.ErrorReplyH\x00R\n" +
	"errorReply\x12?\n" +
	"\fws_signaling\x18\x06 \x01(\v2\x1a.api.webrtc.v1.WSSignalingH\x00R\vwsSignalingB\t\n" +
	"\apayload\"C\n" +
	"\n" +
	"ErrorReply\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"H\n" +
	"\vWSSignaling\x12%\n" +
	"\x0esignaling_type\x18\x01 \x01(\tR\rsignalingType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data*F\n" +
	"\aMsgKind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_ERROR\x10\x01\x12\x15\n" +
	"\x11KIND_WS_SIGNALING\x10\x02B6Z4github.com/bitcoin-sv/KeyRTCServer/api_webrtc/gen/v1b\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_proto_goTypes = []any{
	(MsgKind)(0),                  // 0: api.webrtc.v1.MsgKind
	(*Header)(nil),                // 1: api.webrtc.v1.Header
	(*Envelope)(nil),              // 2: api.webrtc.v1.Envelope
	(*ErrorReply)(nil),            // 3: api.webrtc.v1.ErrorReply
	(*WSSignaling)(nil),           // 4: api.webrtc.v1.WSSignaling
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_message_proto_depIdxs = []int32{
	0, // 0: api.webrtc.v1.Header.kind:type_name -> api.webrtc.v1.MsgKind
	5, // 1: api.webrtc.v1.Header.ts:type_name -> google.protobuf.Timestamp
	1, // 2: api.webrtc.v1.Envelope.header:type_name -> api.webrtc.v1.Header
	3, // 3: api.webrtc.v1.Envelope.error_reply:type_name -> api.webrtc.v1.ErrorReply
	4, // 4: api.webrtc.v1.Envelope.ws_signaling:type_name -> api.webrtc.v1.WSSignaling
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[1].OneofWrappers = []any{
		(*Envelope_ErrorReply)(nil),
		(*Envelope_WsSignaling)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
