// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: message_signaling.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义消息结构,协调通信的过程，系列命令
// 发送给 server 的信息
type SignalingShell struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ForwardPublicKey []byte                 `protobuf:"bytes,1,opt,name=ForwardPublicKey,proto3" json:"ForwardPublicKey,omitempty"`
	Data             []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"` // 加密数据
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignalingShell) Reset() {
	*x = SignalingShell{}
	mi := &file_message_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalingShell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalingShell) ProtoMessage() {}

func (x *SignalingShell) ProtoReflect() protoreflect.Message {
	mi := &file_message_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalingShell.ProtoReflect.Descriptor instead.
func (*SignalingShell) Descriptor() ([]byte, []int) {
	return file_message_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *SignalingShell) GetForwardPublicKey() []byte {
	if x != nil {
		return x.ForwardPublicKey
	}
	return nil
}

func (x *SignalingShell) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_message_signaling_proto protoreflect.FileDescriptor

const file_message_signaling_proto_rawDesc = "" +
	"\n" +
	"\x17message_signaling.proto\x12\rapi.webrtc.v1\"P\n" +
	"\x0eSignalingShell\x12*\n" +
	"\x10ForwardPublicKey\x18\x01 \x01(\fR\x10ForwardPublicKey\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04DataB6Z4github.com/bitcoin-sv/KeyRTCServer/api_webrtc/gen/v1b\x06proto3"

var (
	file_message_signaling_proto_rawDescOnce sync.Once
	file_message_signaling_proto_rawDescData []byte
)

func file_message_signaling_proto_rawDescGZIP() []byte {
	file_message_signaling_proto_rawDescOnce.Do(func() {
		file_message_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_signaling_proto_rawDesc), len(file_message_signaling_proto_rawDesc)))
	})
	return file_message_signaling_proto_rawDescData
}

var file_message_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_signaling_proto_goTypes = []any{
	(*SignalingShell)(nil), // 0: api.webrtc.v1.SignalingShell
}
var file_message_signaling_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_signaling_proto_init() }
func file_message_signaling_proto_init() {
	if File_message_signaling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_signaling_proto_rawDesc), len(file_message_signaling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_signaling_proto_goTypes,
		DependencyIndexes: file_message_signaling_proto_depIdxs,
		MessageInfos:      file_message_signaling_proto_msgTypes,
	}.Build()
	File_message_signaling_proto = out.File
	file_message_signaling_proto_goTypes = nil
	file_message_signaling_proto_depIdxs = nil
}
