// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: message_transaction.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义消息结构
type TransactionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []byte                 `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionMessage) Reset() {
	*x = TransactionMessage{}
	mi := &file_message_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMessage) ProtoMessage() {}

func (x *TransactionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMessage.ProtoReflect.Descriptor instead.
func (*TransactionMessage) Descriptor() ([]byte, []int) {
	return file_message_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionMessage) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

var File_message_transaction_proto protoreflect.FileDescriptor

const file_message_transaction_proto_rawDesc = "" +
	"\n" +
	"\x19message_transaction.proto\x12\rapi.webrtc.v1\"$\n" +
	"\x12TransactionMessage\x12\x0e\n" +
	"\x02tx\x18\x01 \x01(\fR\x02txB6Z4github.com/bitcoin-sv/KeyRTCServer/api_webrtc/gen/v1b\x06proto3"

var (
	file_message_transaction_proto_rawDescOnce sync.Once
	file_message_transaction_proto_rawDescData []byte
)

func file_message_transaction_proto_rawDescGZIP() []byte {
	file_message_transaction_proto_rawDescOnce.Do(func() {
		file_message_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_transaction_proto_rawDesc), len(file_message_transaction_proto_rawDesc)))
	})
	return file_message_transaction_proto_rawDescData
}

var file_message_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_transaction_proto_goTypes = []any{
	(*TransactionMessage)(nil), // 0: api.webrtc.v1.TransactionMessage
}
var file_message_transaction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_transaction_proto_init() }
func file_message_transaction_proto_init() {
	if File_message_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_transaction_proto_rawDesc), len(file_message_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_transaction_proto_goTypes,
		DependencyIndexes: file_message_transaction_proto_depIdxs,
		MessageInfos:      file_message_transaction_proto_msgTypes,
	}.Build()
	File_message_transaction_proto = out.File
	file_message_transaction_proto_goTypes = nil
	file_message_transaction_proto_depIdxs = nil
}
